# Generated by Django 2.1.7 on 2019-03-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('API_link', models.URLField()),
                ('photo', models.URLField()),
                ('nutriscore', models.CharField(max_length=1)),
                ('nutrient_100g', models.TextField(null=True)),
                ('categories', models.ManyToManyField(to='website.Category')),
            ],
        ),
    ]
