# Generated by Django 2.1.7 on 2019-03-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190319_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_category',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='product_category',
            name='product_id',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='website.Category'),
        ),
        migrations.DeleteModel(
            name='Product_Category',
        ),
    ]
