# Generated by Django 2.2 on 2019-04-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20190404_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nutrient_100g',
            field=models.TextField(blank=True, null=True, verbose_name='nutriments(100g)'),
        ),
    ]
